### ISSUE TITLE
Unknown test dependency: server

### ISSUE THREAD

**Issue by pbarill** [seanhess/amqp-worker#3]
Unknown test dependency in `amqp-worker-0.3.2.cabal`: server

Also the [page on hackage](https://hackage.haskell.org/package/amqp-worker) for this package contains a broken link at the top:

> Please see the README on GitHub at https://github.com/seanhess/server#readme

**Comment by seanhess** [comment]
Fixed in 0.4.0. Sorry for the very long delay.
